[editor]
"debugToolBar.background" = "${palette.base_100}"
"editorCursor.foreground" = "${palette.base_content}"
"editorGroup.border" = "${palette.base_100}"
"editorGroup.dropBackground" = "${palette.base_300}40"
"editorGroupHeader.tabsBackground" = "${palette.base_100}"
"editorIndentGuide.activeBackground1" = "${palette.primary}"
"editorIndentGuide.background1" = "${palette.base_300}"
"editorLineNumber.activeForeground" = "${palette.primary}"
"editorLineNumber.foreground" = "${palette.base_300}"
"editorWhitespace.foreground" = "${palette.base_300}"
"editorWidget.background" = "${palette.base_100}"
"focusBorder" = "${palette.primary}"
"inputOption.activeBorder" = "${palette.secondary}"
"minimap.selectionHighlight" = "${palette.base_content}20"
"pickerGroup.foreground" = "${palette.comment}"
"selection.background" = "${palette.base_content}20"
"settings.focusedRowBackground" = "${palette.base_200}"

[editor.quickInput]
background = "${palette.base_200}"
foreground = "${palette.base_content}"

[editor.quickInputList]
focusBackground = "${palette.base_100}"

[editor.editorHoverWidget]
background = "${palette.base_200}"
border = "${palette.base_300}"

[editor.editorSuggestWidget]
background = "${palette.base_100}"
border = "${palette.base_300}"

[editor.gitDecoration]
addedResourceForeground = "${palette.success}"
modifiedResourceForeground = "${palette.info}"
deletedResourceForeground = "${palette.error}"
renamedResourceForeground = "${palette.info}"
stageModifiedResourceForeground = "${palette.warning}"
stageDeletedResourceForeground = "${palette.error}"
untrackedResourceForeground = "${palette.success}"
ignoredResourceForeground = "${palette.neutral}35"
conflictingResourceForeground = "${palette.warning}"
submoduleResourceForeground = "${palette.secondary}"

[editor.activityBar]
activeBorder = "${palette.primary}"
background = "${palette.base_100}"
foreground = "${palette.base_content}"

[editor.activityBarBadge]
background = "${palette.primary}"

[editor.button]
background = "${palette.primary}"
foreground = "${palette.primary_content}"
hoverBackground = "${palette.primary_hover}"

[editor.diffEditor]
insertedTextBackground = "${palette.success}50"
removedTextBackground = "${palette.error}50"

[editor.dropdown]
background = "${palette.base_100}"
listBackground = "${palette.base_100}"

[editor.editor]
background = "${palette.base_100}"
foreground = "${palette.base_content}"
lineHighlightBackground = "${palette.base_200}"
selectionBackground = "${palette.secondary}30"
selectionHighlightBackground = "${palette.primary}30"

[editor.input]
background = "${palette.base_200}"
foreground = "${palette.base_content}"
border = "${palette.base_100}"
placeholderForeground = "${palette.neutral}50"

[editor.inputValidation]
errorBackground = "${palette.error}"
errorBorder = "${palette.secondary}"
infoBackground = "${palette.info}"
infoBorder = "${palette.secondary}"
warningBackground = "${palette.warning}"
warningBorder = "${palette.secondary}"

[editor.list]
activeSelectionBackground = "${palette.base_200}"
activeSelectionForeground = "${palette.base_content}"
dropBackground = "${palette.base_300}40"
hoverBackground = "${palette.base_200}"
errorForeground = "${palette.error}"
highlightForeground = "${palette.base_content}"
inactiveSelectionBackground = "${palette.base_100}"
warningForeground = "${palette.warning}"

[editor.menu]
background = "${palette.base_100}"
foreground = "${palette.base_content}"

[editor.notebook]
cellBorderColor = "${palette.base_300}"
cellEditorBackground = "${palette.base_200}"
cellHoverBackground = "${palette.base_200}"
cellInsertionIndicator = "${palette.primary}"
cellStatusBarItemHoverBackground = "${palette.base_200}"
cellToolbarSeparator = "${palette.base_300}"
focusedCellBackground = "${palette.base_300}"
focusedCellBorder = "${palette.base_100}"
focusedEditorBorder = "${palette.base_content}"
inactiveFocusedCellBorder = "${palette.base_300}"
outputContainerBackgroundColor = "${palette.base_100}"
outputContainerBorderColor = "${palette.base_300}"
selectedCellBackground = "${palette.base_200}"
selectedCellBorder = "${palette.secondary}"

[editor.panel]
background = "${palette.base_100}"
border = "${palette.primary}"

[editor.panelTitle]
activeBorder = "${palette.primary}"
activeForeground = "${palette.base_content}"
inactiveForeground = "${palette.comment}"

[editor.peekView]
border = "${palette.base_300}"

[editor.peekViewTitle]
background = "${palette.base_100}"

[editor.peekViewEditor]
background = "${palette.base_300}"
matchHighlightBackground = "${palette.neutral}50"

[editor.peekViewResult]
background = "${palette.base_100}"
matchHighlightBackground = "${palette.neutral}50"
selectionBackground = "${palette.base_200}"

[editor.sideBar]
background = "${palette.base_100}"
foreground = "${palette.base_content}90"

[editor.sideBarSectionHeader]
background = "${palette.base_100}"
foreground = "${palette.base_content}"
border = "${palette.base_100}"

[editor.sideBarTitle]
foreground = "${palette.base_content}"

[editor.statusBar]
background = "${palette.base_100}"
foreground = "${palette.base_content}"
border = "${palette.base_100}"
noFolderBackground = "${palette.base_100}"

[editor.statusBarItem]
errorBackground = "${palette.error}"
errorForeground = "${palette.base_content}"
prominentBackground = "${palette.primary}"
prominentForeground = "${palette.base_content}"
prominentHoverBackground = "${palette.primary_hover}"
remoteBackground = "${palette.base_100}"
remoteForeground = "${palette.base_content}"
warningBackground = "${palette.warning}"
warningForeground = "${palette.base_content}"

[editor.tab]
activeBorder = "${palette.primary}"
activeForeground = "${palette.base_content}"
border = "${palette.base_100}"
inactiveBackground = "${palette.base_100}"
inactiveForeground = "${palette.secondary}"
lastPinnedBorder = "${palette.secondary}"

# override this in the theme
[editor.terminal]
ansiBlack = "#000000"
ansiBlue = "#0000ff"
ansiBrightBlack = "#fff"
ansiBrightBlue = "#add8e6"
ansiBrightCyan = "#e0ffff"
ansiBrightGreen = "#90ee90"
ansiBrightMagenta = "#ff77ff"
ansiBrightRed = "#ff6347"
ansiBrightWhite = "#ffffff"
ansiBrightYellow = "#ffffe0"
ansiCyan = "#00ffff"
ansiGreen = "#008000"
ansiMagenta = "#ff00ff"
ansiRed = "#ff0000"
ansiWhite = "#c0c0c0"
ansiYellow = "#ffff00"

[editor.titleBar]
activeBackground = "${palette.base_100}"
activeForeground = "${palette.base_content}"
inactiveBackground = "${palette.base_100}"
inactiveForeground = "${palette.base_content}"

[editor.tree]
indentGuidesStroke = "${palette.secondary}50"

[editor.notifications]
background = "${palette.base_200}"
foreground = "${palette.base_content}"
border = "${palette.base_300}"

[editor.notificationCenter]
border = "${palette.base_300}"

[editor.notificationCenterHeader]
background = "${palette.base_200}"
foreground = "${palette.base_content}"

[editor.notificationToast]
border = "${palette.base_300}"

[editor.notificationsErrorIcon]
foreground = "${palette.error}"

[editor.notificationsWarningIcon]
foreground = "${palette.warning}"

[editor.notificationsInfoIcon]
foreground = "${palette.info}"
