[editor]
"titleBar.activeBackground" = "${palette.background}"
"titleBar.activeForeground" = "${palette.foreground}"
"titleBar.inactiveBackground" = "#14161A"
"titleBar.inactiveForeground" = "${palette.comment}"
"activityBar.background" = "${palette.background}"
"activityBar.foreground" = "${palette.foreground}"
"activityBar.activeBorder" = "${palette.primary}"
"activityBarBadge.background" = "${palette.accent}"
"sideBar.background" = "${palette.background}"
"sideBar.foreground" = "${palette.secondary}"
"editor.background" = "${palette.background}"
"editor.foreground" = "${palette.foreground}"
"editorGroupHeader.tabsBackground" = "${palette.background}"
"editorGroup.border" = "${palette.background}"
"editorGroup.dropBackground" = "#ffffff10"
"tab.inactiveBackground" = "${palette.background}"
"tab.inactiveForeground" = "${palette.secondary}"
"tab.border" = "${palette.background}"
"tab.activeBorder" = "${palette.primary}"
"tab.activeForeground" = "${palette.foreground}"
"tab.lastPinnedBorder" = "${palette.secondary}"
"editor.selectionBackground" = "#ffffff20"
"editor.selectionHighlightBackground" = "${palette.primary}30"
"editor.lineHighlightBackground" = "#ffffff08"
"editorLineNumber.foreground" = "#4a4850"
"editorLineNumber.activeForeground" = "${palette.primary}"
"editorCursor.foreground" = "${palette.foreground}"
"editorWhitespace.foreground" = "#4a4850"
"editorIndentGuide.background1" = "#4a4850"
"editorIndentGuide.activeBackground1" = "#7c5dfa"
"editorWidget.background" = "${palette.background}"
"editorSuggestWidget.background" = "#262438"
"editorSuggestWidget.border" = "${palette.secondary}"
"editorHoverWidget.background" = "${palette.background}"
"editorHoverWidget.border" = "${palette.secondary}"
"debugToolBar.background" = "#3d2c5a"
"menu.background" = "${palette.background}"
"menu.foreground" = "${palette.foreground}"
"dropdown.background" = "${palette.background}"
"dropdown.listBackground" = "${palette.background}"
"input.background" = "#262438"
"input.foreground" = "${palette.foreground}"
"inputOption.activeBorder" = "${palette.secondary}"
"quickInput.background" = "#262438"
"quickInput.foreground" = "${palette.foreground}"
"quickInputList.focusBackground" = "${palette.background}"
"pickerGroup.foreground" = "${palette.comment}"
"focusBorder" = "${palette.primary}"
"settings.focusedRowBackground" = "#262438"
"list.inactiveSelectionBackground" = "${palette.background}"
"list.activeSelectionBackground" = "#262438"
"list.hoverBackground" = "#262438"
"list.highlightForeground" = "${palette.foreground}"
"list.errorForeground" = "${palette.error}"
"list.warningForeground" = "${palette.warning}"
"list.dropBackground" = "#ffffff10"
"peekView.border" = "${palette.primary}"
"peekViewTitle.background" = "${palette.background}"
"peekViewResult.background" = "${palette.background}"
"peekViewResult.selectionBackground" = "${palette.background}"
"peekViewResult.matchHighlightBackground" = "${palette.comment}"
"peekViewEditor.background" = "#262438"
"peekViewEditor.matchHighlightBackground" = "${palette.comment}"
"panel.background" = "${palette.background}"
"panel.border" = "${palette.primary}"
"panelTitle.activeBorder" = "${palette.primary}"
"panelTitle.activeForeground" = "${palette.foreground}"
"panelTitle.inactiveForeground" = "${palette.comment}"
"sideBarSectionHeader.background" = "${palette.background}"
"diffEditor.insertedTextBackground" = "${palette.success}70"
"diffEditor.removedTextBackground" = "${palette.error}50"
"diffEditorGutter.insertedLineBackground" = "${palette.success}70"
"diffEditorGutter.removedLineBackground" = "${palette.error}50"
"gitDecoration.addedResourceForeground" = "${palette.success}"
"gitDecoration.modifiedResourceForeground" = "${palette.accent}"
"gitDecoration.deletedResourceForeground" = "${palette.error}"
"gitDecoration.untrackedResourceForeground" = "${palette.info}"
"gitDecoration.ignoredResourceForeground" = "${palette.secondary}"
"gitDecoration.conflictingResourceForeground" = "${palette.info}"
"gitDecoration.submoduleResourceForeground" = "${palette.info}"
"gitDecoration.stageModifiedResourceForeground" = "${palette.info}"
"gitDecoration.stageDeletedResourceForeground" = "${palette.info}"
"gitDecoration.renamedResourceForeground" = "${palette.info}"
"editorGutter.background" = "${palette.background}"
"editorGutter.addedBackground" = "${palette.success}"
"editorGutter.deletedBackground" = "${palette.error}"
"editorGutter.modifiedBackground" = "${palette.primary}"
"inputValidation.errorBackground" = "#8b1538"
"inputValidation.errorBorder" = "${palette.secondary}"
"inputValidation.warningBackground" = "#b87400"
"inputValidation.warningBorder" = "${palette.secondary}"
"inputValidation.infoBackground" = "#5d4d7a"
"inputValidation.infoBorder" = "${palette.secondary}"
"button.background" = "${palette.primary}"
"button.foreground" = "${palette.foreground}"
"button.hoverBackground" = "${palette.primary_hover}"
"progressBar.background" = "${palette.primary}"
"badge.background" = "${palette.primary}"
"badge.foreground" = "${palette.foreground}"
"statusBar.background" = "${palette.background}"
"statusBar.foreground" = "${palette.foreground}"
"statusBar.border" = "${palette.background}"
"statusBar.debuggingBackground" = "${palette.error}"
"statusBar.debuggingForeground" = "${palette.foreground}"
"statusBar.debuggingBorder" = "${palette.error}"
"statusBar.noFolderBackground" = "${palette.background}"
"statusBar.noFolderForeground" = "${palette.foreground}"
"statusBar.noFolderBorder" = "${palette.background}"
"statusBarItem.prominentBackground" = "${palette.primary}"
"statusBarItem.prominentForeground" = "${palette.foreground}"
"statusBarItem.prominentHoverBackground" = "${palette.primary_hover}"
"statusBarItem.errorBackground" = "${palette.error}"
"statusBarItem.errorForeground" = "${palette.foreground}"
"statusBarItem.warningBackground" = "${palette.warning}"
"statusBarItem.warningForeground" = "${palette.foreground}"
"statusBarItem.remoteBackground" = "${palette.primary}"
"statusBarItem.remoteForeground" = "${palette.foreground}"
"ports.iconRunningProcessForeground" = "${palette.secondary}"
"selection.background" = "#ffffff20"
"minimap.selectionHighlight" = "#ffffff20"
"widget.shadow" = "#00000080"
"terminal.ansiBlack" = "#4a4850"
"terminal.ansiRed" = "${palette.error}"
"terminal.ansiGreen" = "#37946A"
"terminal.ansiYellow" = "${palette.warning}"
"terminal.ansiBlue" = "${palette.info}"
"terminal.ansiMagenta" = "${palette.accent}"
"terminal.ansiCyan" = "#0891b2"
"terminal.ansiWhite" = "${palette.foreground}"
"terminal.ansiBrightBlack" = "${palette.comment}"
"terminal.ansiBrightRed" = "#ff4d94"
"terminal.ansiBrightGreen" = "#37946A"
"terminal.ansiBrightYellow" = "${palette.warning}"
"terminal.ansiBrightBlue" = "#4d9eff"
"terminal.ansiBrightMagenta" = "#c77dff"
"terminal.ansiBrightCyan" = "#19d4ff"
"terminal.ansiBrightWhite" = "#ffffff"
"notebook.cellEditorBackground" = "#262438"
"notebook.cellBorderColor" = "${palette.background}"
"notebook.cellHoverBackground" = "#262438"
"notebook.focusedCellBorder" = "${palette.primary}"
"notebook.focusedCellBackground" = "#262438"
"notebook.focusedEditorBorder" = "${palette.primary}"
"notebook.cellInsertionIndicator" = "#ffffff"
