[editor]
"editorGroupHeader.tabsBackground" = "${palette.background}"
"editorGroup.border" = "${palette.background}"
"editorGroup.dropBackground" = "#ffffff10"
"editorLineNumber.foreground" = "#4a4850"
"editorLineNumber.activeForeground" = "${palette.primary}"
"editorCursor.foreground" = "${palette.foreground}"
"editorWhitespace.foreground" = "#4a4850"
"editorIndentGuide.background1" = "#4a4850"
"editorIndentGuide.activeBackground1" = "#7c5dfa"
"editorWidget.background" = "${palette.background}"
"editorSuggestWidget.background" = "#262438"
"editorSuggestWidget.border" = "${palette.secondary}"
"editorHoverWidget.background" = "${palette.background}"
"editorHoverWidget.border" = "${palette.secondary}"
"debugToolBar.background" = "#3d2c5a"
"inputOption.activeBorder" = "${palette.secondary}"
"quickInput.background" = "#262438"
"quickInput.foreground" = "${palette.foreground}"
"quickInputList.focusBackground" = "${palette.background}"
"pickerGroup.foreground" = "${palette.comment}"
"focusBorder" = "${palette.primary}"
"settings.focusedRowBackground" = "#262438"
"selection.background" = "#ffffff20"
"minimap.selectionHighlight" = "#ffffff20"
"widget.shadow" = "#00000080"
"peekView.border" = "#7c5dfa"
"peekViewTitle.background" = "#090B0F"

[editor.menu]
background = "${palette.background}"
foreground = "${palette.foreground}"

[editor.dropdown]
background = "${palette.background}"
listBackground = "${palette.background}"

[editor.input]
background = "#262438"
foreground = "${palette.foreground}"

[editor.editor]
background = "${palette.background}"
foreground = "${palette.foreground}"
selectionBackground = "#ffffff20"
selectionHighlightBackground = "${palette.primary}30"
lineHighlightBackground = "#ffffff08"

[editor.statusBarItem]
prominentBackground = "${palette.primary}"
prominentForeground = "${palette.foreground}"
prominentHoverBackground = "${palette.primary_hover}"
errorBackground = "${palette.error}"
errorForeground = "${palette.foreground}"
warningBackground = "${palette.warning}"
warningForeground = "${palette.foreground}"
remoteBackground = "${palette.primary}"
remoteForeground = "${palette.foreground}"

[editor.titleBar]
activeBackground = "${palette.background}"
activeForeground = "${palette.foreground}"
inactiveBackground = "#14161A"
inactiveForeground = "${palette.comment}"

[editor.activityBar]
background = "${palette.background}"
foreground = "${palette.foreground}"
activeBorder = "${palette.primary}"

[editor.activityBarBadge]
background = "${palette.accent}"

[editor.sideBar]
background = "${palette.background}"
foreground = "${palette.secondary}"

[editor.tab]
inactiveBackground = "${palette.background}"
inactiveForeground = "${palette.secondary}"
border = "${palette.background}"
activeBorder = "${palette.primary}"
activeForeground = "${palette.foreground}"
lastPinnedBorder = "${palette.secondary}"

[editor.diffEditor]
insertedTextBackground = "${palette.success}70"
removedTextBackground = "${palette.error}50"

[editor.terminal]
ansiBlack = "#4a4850"
ansiRed = "${palette.error}"
ansiGreen = "#37946A"
ansiYellow = "${palette.warning}"
ansiBlue = "${palette.info}"
ansiMagenta = "${palette.accent}"
ansiCyan = "#0891b2"
ansiWhite = "${palette.foreground}"
ansiBrightBlack = "${palette.comment}"
ansiBrightRed = "#ff4d94"
ansiBrightGreen = "#37946A"
ansiBrightYellow = "${palette.warning}"
ansiBrightBlue = "#4d9eff"
ansiBrightMagenta = "#c77dff"
ansiBrightCyan = "#19d4ff"
ansiBrightWhite = "#ffffff"

[editor.notebook]
cellEditorBackground = "#262438"
cellBorderColor = "${palette.background}"
cellHoverBackground = "#262438"
focusedCellBorder = "${palette.primary}"
focusedCellBackground = "#262438"
focusedEditorBorder = "${palette.primary}"
cellInsertionIndicator = "#ffffff"

[editor.list]
inactiveSelectionBackground = "${palette.background}"
activeSelectionBackground = "#262438"
hoverBackground = "#262438"
highlightForeground = "${palette.foreground}"
errorForeground = "${palette.error}"
warningForeground = "${palette.warning}"
dropBackground = "#ffffff10"

[editor.panel]
background = "${palette.background}"
border = "${palette.primary}"

[editor.panelTitle]
activeBorder = "${palette.primary}"
activeForeground = "${palette.foreground}"
inactiveForeground = "${palette.comment}"

[editor.inputValidation]
errorBackground = "#8b1538"
errorBorder = "${palette.secondary}"
warningBackground = "#b87400"
warningBorder = "${palette.secondary}"
infoBackground = "#5d4d7a"
infoBorder = "${palette.secondary}"

[editor.peekViewResult]
background = "#090B0F"
selectionBackground = "#090B0F"
matchHighlightBackground = "#79767d"

[editor.peekViewEditor]
background = "#262438"
matchHighlightBackground = "#79767d"
