[editor]
"debugToolBar.background" = "#3d2c5a"
"editorCursor.foreground" = "${palette.foreground}"
"editorGroup.border" = "${palette.background}"
"editorGroup.dropBackground" = "#ffffff10"
"editorGroupHeader.tabsBackground" = "${palette.background}"
"editorHoverWidget.background" = "${palette.background}"
"editorHoverWidget.border" = "${palette.secondary}"
"editorIndentGuide.activeBackground1" = "#7c5dfa"
"editorIndentGuide.background1" = "#4a4850"
"editorLineNumber.activeForeground" = "${palette.primary}"
"editorLineNumber.foreground" = "#4a4850"
"editorSuggestWidget.background" = "#262438"
"editorSuggestWidget.border" = "${palette.secondary}"
"editorWhitespace.foreground" = "#4a4850"
"editorWidget.background" = "${palette.background}"
"focusBorder" = "${palette.primary}"
"inputOption.activeBorder" = "${palette.secondary}"
"minimap.selectionHighlight" = "#ffffff20"
"peekView.border" = "#7c5dfa"
"peekViewTitle.background" = "#090B0F"
"pickerGroup.foreground" = "${palette.comment}"
"quickInput.background" = "#262438"
"quickInput.foreground" = "${palette.foreground}"
"quickInputList.focusBackground" = "${palette.background}"
"selection.background" = "#ffffff20"
"settings.focusedRowBackground" = "#262438"
"widget.shadow" = "#00000080"

[editor.activityBar]
activeBorder = "${palette.primary}"
background = "${palette.background}"
foreground = "${palette.foreground}"

[editor.activityBarBadge]
background = "${palette.accent}"

[editor.diffEditor]
insertedTextBackground = "${palette.success}70"
removedTextBackground = "${palette.error}50"

[editor.dropdown]
background = "${palette.background}"
listBackground = "${palette.background}"

[editor.editor]
background = "${palette.background}"
foreground = "${palette.foreground}"
lineHighlightBackground = "#ffffff08"
selectionBackground = "#ffffff20"
selectionHighlightBackground = "${palette.primary}30"

[editor.input]
background = "#262438"
foreground = "${palette.foreground}"

[editor.inputValidation]
errorBackground = "#8b1538"
errorBorder = "${palette.secondary}"
infoBackground = "#5d4d7a"
infoBorder = "${palette.secondary}"
warningBackground = "#b87400"
warningBorder = "${palette.secondary}"

[editor.list]
activeSelectionBackground = "#262438"
dropBackground = "#ffffff10"
errorForeground = "${palette.error}"
highlightForeground = "${palette.foreground}"
hoverBackground = "#262438"
inactiveSelectionBackground = "${palette.background}"
warningForeground = "${palette.warning}"

[editor.menu]
background = "${palette.background}"
foreground = "${palette.foreground}"

[editor.notebook]
cellBorderColor = "${palette.background}"
cellEditorBackground = "#262438"
cellHoverBackground = "#262438"
cellInsertionIndicator = "#ffffff"
focusedCellBackground = "#262438"
focusedCellBorder = "${palette.primary}"
focusedEditorBorder = "${palette.primary}"

[editor.panel]
background = "${palette.background}"
border = "${palette.primary}"

[editor.panelTitle]
activeBorder = "${palette.primary}"
activeForeground = "${palette.foreground}"
inactiveForeground = "${palette.comment}"

[editor.peekViewEditor]
background = "#262438"
matchHighlightBackground = "#79767d"

[editor.peekViewResult]
background = "#090B0F"
matchHighlightBackground = "#79767d"
selectionBackground = "#090B0F"

[editor.sideBar]
background = "${palette.background}"
foreground = "${palette.secondary}"

[editor.statusBarItem]
errorBackground = "${palette.error}"
errorForeground = "${palette.foreground}"
prominentBackground = "${palette.primary}"
prominentForeground = "${palette.foreground}"
prominentHoverBackground = "${palette.primary_hover}"
remoteBackground = "${palette.primary}"
remoteForeground = "${palette.foreground}"
warningBackground = "${palette.warning}"
warningForeground = "${palette.foreground}"

[editor.tab]
activeBorder = "${palette.primary}"
activeForeground = "${palette.foreground}"
border = "${palette.background}"
inactiveBackground = "${palette.background}"
inactiveForeground = "${palette.secondary}"
lastPinnedBorder = "${palette.secondary}"

[editor.terminal]
ansiBlack = "#4a4850"
ansiBlue = "${palette.info}"
ansiBrightBlack = "${palette.comment}"
ansiBrightBlue = "#4d9eff"
ansiBrightCyan = "#19d4ff"
ansiBrightGreen = "#37946A"
ansiBrightMagenta = "#c77dff"
ansiBrightRed = "#ff4d94"
ansiBrightWhite = "#ffffff"
ansiBrightYellow = "${palette.warning}"
ansiCyan = "#0891b2"
ansiGreen = "#37946A"
ansiMagenta = "${palette.accent}"
ansiRed = "${palette.error}"
ansiWhite = "${palette.foreground}"
ansiYellow = "${palette.warning}"

[editor.titleBar]
activeBackground = "${palette.background}"
activeForeground = "${palette.foreground}"
inactiveBackground = "#14161A"
inactiveForeground = "${palette.comment}"
