[class]
name = "Class name"
color = "#ECEEF5"
scope = ["entity.name.type", "entity.name.class", "entity.name.namespace", "entity.name.scope-resolution"]

[comment]
color = "comment"
scope = ["comment", "definition.comment"]

[constant]
color = "base_content"
scope = [".character", ".other"]

[constant.language]
color = "error"

[entity.name.filename.find-in-files]
name = "Filename in Find in Files"
color = "#FCFD28"

[entity.other.attribute-name]
name = "Tag attribute"
color = "warning"

[function]
color = "string"
name = "Function name"
scope = ["entity.name.function", "meta.function-call.python", "new.expr.js"]

[inherited_class]
color = "#e0cbff"
name = "Inherited class"
scope = "entity.other.inherited-class"
style = "italic underline"

[invalid]
color = "#F44747"
name = "Invalid"
scope = "invalid"

[json_string]
name = "JSON String"
color = "#CFCFC2"
scope = ["meta.structure.dictionary.json", "string.quoted.double.json"]

[keyword]
scope = ["keyword", "support.type.property-name.json"]
color = "primary_hover"

[keyword.operator.ternary]
scope = [
  ".jsx",
  ".js",
  ".ts",
  ".tsx"
]
color = "error"

[library_constant]
color = "primary_hover"
name = "Library constant"
scope = "support.constant"

[library_function]
color = "primary_hover"
name = "Library function"
scope = "support.function"

[library_variable]
name = "Library variable"
scope = "support.other.variable"

[line_number]
color = "#ec4899A0"
scope = "constant.numeric.line-number.find-in-files - match"

[markdown_bold]
name = "Markdown Bold"
scope = "markup.bold.markdown"
style = "bold"

[markdown_emphasis]
name = "Markdown Emphasis"
scope = "markup.italic.markdown"
style = "italic"

[markdown_link_title_description]
color = "error"
group = true
name = "Markdown Link Title/Description"

[markdown_link_title_description.string.other.link.description.markdown]
color = "error"
scope = "string.other.link.description.markdown"

[markdown_link_title_description.string.other.link.title.markdown]
color = "error"
scope = "string.other.link.title.markdown"

[markdown_list_punctuation]
color = "primary"
name = "Markdown List Punctuation"
scope = ["punctuation.definition.list.begin.markdown"]

[markup]
name = "Markup Styling"
scope = [".bold", ".italic"]
color = "#faf5ff"

[markup.changed]
color = "#8b5cf6"

[markup.deleted]
color = "#F811A0"

[markup.heading]
color = "#ec4899"

[markup.heading.setext]
color = "#ec4899"
style = "bold"

[markup.inline.raw]
color = "#EC0095"

[markup.inserted]
color = "#f4a14d"

[markup.list]
scope = [".numbered.markdown", ".unnumbered.markdown"]
color = "#f8f8f2"

[markup.quote]
color = "#F811A0"

[markup.quote.markdown]
color = "#e5e7eb"
style = "italic"

[markup.strikethrough]
style = "strikethrough"

[markup.underline.link]
scope = [".markdown", ".image.markdown"]
color = "base_content"

[meta.brace]
scope = [
  ".round.jsx",
  ".square.jsx",
  ".round.js",
  ".square.js",
  ".round.ts",
  ".square.ts",
  ".round.tsx",
  ".square.tsx"
]
color = "error"

[meta.diff]
scope = ["meta.diff", "diff.header", ".header"]
color = "#75715E"

[number]
color = "error"
name = "Number"
scope = "constant.numeric"

[punctuation]
color = "comment"
name = "Punctuation"
scope = [".definition", ".separator", ".terminator", ".accessor.optional.js.jsx"]

[punctuation.definition.binding-pattern]
name = "Punctuation Definition"
scope = [
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".binding-pattern.object.js",
  ".binding-pattern.object.jsx",
  ".binding-pattern.object.ts",
  ".binding-pattern.object.tsx"
]
color = "comment"

[punctuation.definition.block]
name = "Punctuation Definition"
scope = [
  ".js",
  ".jsx",
  ".ts",
  ".tsx"
]
color = "comment"

[punctuation.definition.template-expression]
scope = [
  ".begin.jsx",
  ".end.jsx",
  ".begin.js",
  ".end.js",
  ".begin.ts",
  ".end.ts",
  ".begin.tsx",
  ".end.tsx"
]
color = "error"

[punctuation.section]
color = "primary"
name = "Punctuation Section"
scope = [".embedded.begin.js", ".embedded.end.js", ".embedded.begin.jsx", ".embedded.end.jsx"]

[punctuation.section.embedded]
scope = [
  "punctuation.section.embedded.begin.js",
  "punctuation.section.embedded.end.js",
  "punctuation.section.embedded.begin.jsx",
  "punctuation.section.embedded.end.jsx",
  "punctuation.section.embedded.begin.ts",
  "punctuation.section.embedded.end.ts",
  "punctuation.section.embedded.begin.tsx",
  "punctuation.section.embedded.end.tsx"
]
color = "error"

[reset]
name = "Reset JavaScript string interpolation expression"
scope = "meta.template.expression"
color = "base_content"

[storage]
color = "base_content"
name = "Storage"
scope = "storage"

[storage.type]
color = "primary_hover"
style = "italic"

[string]
color = "string"

[support]
name = "Library class/type"
scope = [".type", ".class"]
color = "string"
style = "italic"

[tag_name]
color = "#8B8DFF"
name = "Tag name"
scope = ["entity.name.tag", "support.class.component.jsx", "support.class.component.js", "support.class.component.ts", "support.class.component.tsx"]

[template]
color = "primary"
name = "Template Definition"
scope = ["punctuation.definition.template-expression", "punctuation.section.embedded"]

[token.debug-token]
color = "#dcdcaa"

[token.error-token]
color = "#f44747"

[token.info-token]
color = "#6796e6"

[token.warn-token]
color = "#cca700"

[variable]
color = "base_content"
