[import]
editor = "../../templates/zed/editor.toml"
syntax = "../../templates/zed/syntax.toml"

[metadata]
name = "Looped Light"
type = "light"

[palette]
base_100 = "#FFFFFF"
base_200 = "#F5F5F5"
base_300 = "#E0E0E0"
base_content = "#1A1A1A"
primary = "#685EF6"
primary_hover = "#685ef6d5"
primary_content = "#FFFFFF"
secondary = "#8B8DFF"
accent = "#4A1ED9"
neutral = "#6B6B6B"
info = "#5B7FFF"
error = "#D02E1E"
success = "#2D7A54"
warning = "#E68A00"
comment = "#9E9E9E"
string = "#6B5FD9"
number = "#5B8FCC"
boolean = "#7E5DE9"
operator = "#685EF6"
keyword = "#685EF6"
variable = "#1A1A1A"
constant = "#6B5FD9"
function_name = "#1A1A1A"
tag = "#D93651"
attribute = "#5B8FCC"
