[import]
editor = "../templates/editor.toml"
syntax = "../templates/syntax.toml"

[metadata]
name = "Looped Dark"
semanticHighlighting = true
type = "dark"

[palette]
base_100 = "#0A0B10"
base_200 = "#14161B"
base_300 = "#313338"
base_content = "#FAF9F6"
primary = "#685EF6"
primary_hover = "#685ef6d5"
primary_content = "#FFFFFF"
secondary = "#8B8DFF"
accent = "#4A1ED9"
neutral = "#EDEEF5"
comment = "#616369"
string = "#888BFF"
info = "#8B8DFF"
error = "#D02E1E"
success = "#389469"
warning = "#EE9A00"
