[import]
editor = "../templates/code/editor.toml"
syntax = "../templates/code/syntax.toml"
zed_editor = "../templates/zed/editor.toml"
zed_syntax = "../templates/zed/syntax.toml"

[metadata]
name = "Looped Dark"
semanticHighlighting = true
type = "dark"

[palette]
base_100 = "#0A0B10"
base_200 = "#14161B"
base_300 = "#313338"
base_content = "#FAF9F6"
primary = "#685EF6"
primary_hover = "#685ef6d5"
primary_content = "#FFFFFF"
secondary = "#8B8DFF"
accent = "#4A1ED9"
neutral = "#EDEEF5"
info = "#8B8DFF"
error = "#D02E1E"
success = "#389469"
warning = "#EE9A00"
comment = "#616369"
string = "#8B8DFF"
number = "#8CB8FF"
boolean = "#7E5DE9"
operator = "#8B8DFF"
keyword = "#685EF6"
variable = "#FAF9F6"
constant = "#8B8DFF"
function_name = "#FAF9F6"
tag = "#FF5C69"
attribute = "#8CB8FF"
