# Zed Editor UI Colors - Comprehensive Template
# Based on Zed v0.2.0 theme schema

# Root-level properties
[root]
background = "${palette.base_100}"
foreground = "${palette.base_content}"
border = "${palette.base_300}"
text = "${palette.base_content}"
icon = "${palette.base_content}"

# Borders
[border]
variant = "${palette.base_300}"
focused = "${palette.primary}"
selected = "${palette.primary}"
transparent = "#00000000"
disabled = "${palette.base_300}50"

# Surfaces
[elevated_surface]
background = "${palette.base_200}"

[surface]
background = "${palette.base_100}"

# Elements
[element]
background = "${palette.base_100}"
hover = "${palette.base_200}"
active = "${palette.primary}30"
selected = "${palette.primary}20"
disabled = "${palette.base_300}30"

# Ghost Elements
[ghost_element]
background = "transparent"
hover = "${palette.base_200}50"
active = "${palette.primary}20"
selected = "${palette.primary}15"
disabled = "${palette.base_300}20"

# Drop Target
[drop_target]
background = "${palette.primary}30"

# Text
[text]
muted = "${palette.comment}"
placeholder = "${palette.base_300}"
disabled = "${palette.base_300}50"
accent = "${palette.primary}"

# Icons
[icon]
muted = "${palette.comment}"
disabled = "${palette.base_300}50"
placeholder = "${palette.base_300}"
accent = "${palette.primary}"

# Status Bar
[status_bar]
background = "${palette.base_100}"

# Title Bar
[title_bar]
background = "${palette.base_100}"
inactive_background = "${palette.base_100}"

# Toolbar
[toolbar]
background = "${palette.base_100}"

# Tab Bar
[tab_bar]
background = "${palette.base_100}"

[tab]
inactive_background = "${palette.base_200}"
active_background = "${palette.base_100}"

# Search
[search]
match_background = "${palette.warning}40"

# Panel
[panel]
background = "${palette.base_100}"
focused_border = "${palette.primary}"

# Pane
[pane]
focused_border = "${palette.primary}"

# Scrollbar
[scrollbar.thumb]
background = "${palette.base_300}80"
hover_background = "${palette.base_300}"
border = "${palette.base_300}"

[scrollbar.track]
background = "transparent"
border = "${palette.base_300}"

# Editor
[editor]
foreground = "${palette.base_content}"
background = "${palette.base_100}"
line_number = "${palette.base_300}"
active_line_number = "${palette.primary}"
hover_line_number = "${palette.base_content}"
invisible = "${palette.base_300}30"
wrap_guide = "${palette.base_300}30"
active_wrap_guide = "${palette.base_300}"

[editor.gutter]
background = "${palette.base_100}"

[editor.subheader]
background = "${palette.base_100}"

[editor.active_line]
background = "${palette.base_100}"

[editor.highlighted_line]
background = "${palette.primary}15"

[editor.document_highlight]
read_background = "${palette.info}30"
write_background = "${palette.warning}30"

# Terminal
[terminal]
background = "${palette.base_100}"
foreground = "${palette.base_content}"
bright_foreground = "${palette.base_content}"
dim_foreground = "${palette.comment}"

# Terminal ANSI Colors
[terminal.ansi]
black = "#000000"
red = "${palette.error}"
green = "${palette.success}"
yellow = "${palette.warning}"
blue = "${palette.info}"
magenta = "${palette.primary}"
cyan = "${palette.secondary}"
white = "${palette.base_content}"
bright_black = "${palette.base_300}"
bright_red = "${palette.error}"
bright_green = "${palette.success}"
bright_yellow = "${palette.warning}"
bright_blue = "${palette.info}"
bright_magenta = "${palette.primary}"
bright_cyan = "${palette.secondary}"
bright_white = "${palette.base_content}"
dim_black = "#00000080"
dim_red = "${palette.error}80"
dim_green = "${palette.success}80"
dim_yellow = "${palette.warning}80"
dim_blue = "${palette.info}80"
dim_magenta = "${palette.primary}80"
dim_cyan = "${palette.secondary}80"
dim_white = "${palette.base_content}80"

# Link Text
[link_text]
hover = "${palette.primary}"

# Version Control
[version_control]
added = "${palette.success}"
modified = "${palette.info}"
deleted = "${palette.error}"

# Status Indicators
[conflict]
color = "${palette.warning}"
background = "${palette.warning}1a"
border = "${palette.warning}50"

[created]
color = "${palette.success}"
background = "${palette.success}1a"
border = "${palette.success}50"

[deleted]
color = "${palette.error}"
background = "${palette.error}1a"
border = "${palette.error}50"

[error]
color = "${palette.error}"
background = "${palette.error}1a"
border = "${palette.error}50"

[hidden]
color = "${palette.comment}"
background = "${palette.comment}1a"
border = "${palette.base_300}"

[hint]
color = "${palette.primary}"
background = "${palette.primary}1a"
border = "${palette.primary}50"

[ignored]
color = "${palette.comment}"
background = "${palette.comment}1a"
border = "${palette.base_300}"

[info]
color = "${palette.info}"
background = "${palette.info}1a"
border = "${palette.info}50"

[modified]
color = "${palette.warning}"
background = "${palette.warning}1a"
border = "${palette.warning}50"

[predictive]
color = "${palette.comment}"
background = "${palette.comment}1a"
border = "${palette.base_300}"

[renamed]
color = "${palette.info}"
background = "${palette.info}1a"
border = "${palette.info}50"

[success]
color = "${palette.success}"
background = "${palette.success}1a"
border = "${palette.success}50"

[unreachable]
color = "${palette.comment}"
background = "${palette.comment}1a"
border = "${palette.base_300}"

[warning]
color = "${palette.warning}"
background = "${palette.warning}1a"
border = "${palette.warning}50"
