name: Mirror Zed themes to zed-theme repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror-zed:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-zed
      cancel-in-progress: true
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build Zed themes
        run: uv run build_zed.py

      - name: Mirror zed/ to loopedautomation/zed-theme (force push)
        env:
          TARGET_REPO: loopedautomation/zed-theme
          TOKEN: ${{ secrets.ZED_THEME_PAT }}
        run: |
          set -euo pipefail

          if [ -z "${TOKEN:-}" ]; then
            echo "Missing ZED_THEME_PAT secret"
            exit 1
          fi

          if [ ! -d "zed" ]; then
            echo "No zed/ directory present. Aborting."
            exit 1
          fi

          echo "Preparing temporary repo..."
          TMP=zed-repo
          rm -rf "$TMP"
          mkdir -p "$TMP"
          cd "$TMP"

          # Initialize repo and add remote authenticated with PAT
          git init
          git remote add origin "https://x-access-token:${TOKEN}@github.com/${TARGET_REPO}.git"

          # Ensure we're on main branch locally
          git checkout -B main

          # Remove any files (should be empty repo, but safe to clean)
          git rm -rf . || true

          echo "Copying built zed/ contents into repo root..."
          rsync -a --delete ../zed/ ./

          echo "Configuring committer identity..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Staging files..."
          git add -A

          echo "Committing..."
          git commit --allow-empty -m "Mirror zed/ from editor-themes@${{ github.sha }}"

          echo "Force-pushing to ${TARGET_REPO}:main"
          # Force update the remote main branch to match the contents of zed/
          git push origin main --force
