name: Mirror Zed themes to zed-theme repo

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  mirror-zed:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-zed
      cancel-in-progress: true
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Build Zed themes
        run: uv run build_zed.py

      - name: Mirror zed/ to loopedautomation/zed-theme (force push)
        env:
          TARGET_REPO: loopedautomation/zed-theme
          TOKEN: ${{ secrets.ZED_THEME_PAT }}
        run: |
          set -euo pipefail

          if [ -z "${TOKEN:-}" ]; then
            echo "Missing ZED_THEME_PAT secret"
            exit 1
          fi

          if [ ! -d "zed" ]; then
            echo "No zed/ directory present. Aborting."
            exit 1
          fi

          echo "Preparing temporary repo (outside workspace)..."
          TMP_DIR=$(mktemp -d)
          echo "Using temp dir: $TMP_DIR"
          # Ensure we operate outside the repository workspace to avoid accidental pushes to this repo
          cd "$TMP_DIR"

          # Initialize repo and add remote authenticated with PAT
          git init
          git remote add origin "https://x-access-token:${TOKEN}@github.com/${TARGET_REPO}.git"

          # Ensure branch 'main' exists locally
          git checkout -B main

          # Clean any pre-existing files except .git
          find . -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} + || true

          echo "Copying built zed/ contents into repo root from workspace..."
          # Use GITHUB_WORKSPACE to reference the checked-out source repository workspace
          if [ -z "${GITHUB_WORKSPACE:-}" ]; then
            # Fallback: assume parent directory contains checked-out repo
            SRC_ROOT="$(pwd)/../editor-themes"
          else
            SRC_ROOT="$GITHUB_WORKSPACE"
          fi

          echo "Source root: $SRC_ROOT"
          rsync -a --delete "$SRC_ROOT/zed/" ./

          # Remove any accidental .git from copied files
          rm -rf .git || true

          echo "Configuring committer identity..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Staging files..."
          git add -A

          echo "Committing..."
          git commit --allow-empty -m "Mirror zed/ from editor-themes@${{ github.sha }}"

          echo "Force-pushing to ${TARGET_REPO}:main"
          # Force update the remote main branch to match the contents of zed/
          git push origin main --force

          # Cleanup temp dir
          cd /
          rm -rf "$TMP_DIR" || true
